version: "3"

services:
  sonarqube:
    image: mc1arke/sonarqube-with-community-branch-plugin:8.9-community
    depends_on:
      - init
      - db
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    container_name: sonarqube
    ports:
      - "80:9000"
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072

    db:
      image: postgres:11
      restart: unless-stopped
      environment:
        - POSTGRES_USER=sonarqube
        - POSTGRES_PASSWORD=sonarpass
        - POSTGRES_DB=sonarqube
      container_name: postgres
      networks:
        - sonarnet
      volumes:
        - postgresql:/var/lib/postgresql
        - postgresql_data:/var/lib/postgresql/data

    init:
      image: bash
      restart: unless-stopped
      privileged: true
      user: root
      container_name: sonarqube_init
      networks:
        - sonarnet
      volumes:
        - ./init.sh:/mnt/init.sh
      command: [ "sh", "-e", "/mnt/init.sh" ]

volumes:
  postgresql:
  postgresql_data:
  sonarqube_conf:
  sonarqube_data:

networks:
  sonarnet:
